name: Release Project

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version (e.g. 1.0.0)'
        required: true
        type: string
      developmentVersion:
        description: 'Next development version (e.g. 1.0.1-SNAPSHOT)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push commits and tags
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Set release version
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}

      - name: Commit release version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Release version ${{ github.event.inputs.releaseVersion }}"
          git push

      - name: Tag release
        run: |
          git tag ${{ github.event.inputs.releaseVersion }}
          git push origin ${{ github.event.inputs.releaseVersion }}

      - name: Trigger Build
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type":"trigger-build"}'

      - name: Set next development version
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.developmentVersion }}

      - name: Commit next development version
        run: |
          git commit -am "Start next development version ${{ github.event.inputs.developmentVersion }}"
          git push
